### ISSUE TITLE
Getting Modules for RMD

### ISSUE THREAD

**Issue by imk1** [gifford-lab/GEM#1]
How do I get which TF belongs to each module from the output of RMD?  Thanks!

**Comment by yguoma** [comment]
Each module is a multinomial distribution over all the TFs. I would suggest start from the module-TF matrix (i.e. the topic matrix), take a cutoff (say, 1 standard deviation of each module vector) to get the main TFs in the module.

**Comment by yguoma** [comment]
I would add that this has been described in the RMD paper.

**Comment by imk1** [comment]
All of this makes sense, but I am having trouble figure out what this corresponds to in terms of the output files.  I cannot find anything that seems to correspond to a module x TF matrix.  What is the suffix of the file with this information?  Thanks!

**Comment by yguoma** [comment]
If you have run HDP successfully, you should have files like
00000-topic.dat, with the digits being the iteration number. This is the
topic matrix at that iteration. It is number of TF sites in the topics
(rows).

You may want to use the state.log file to check the convergence of the
model training process. You can also see which iteration gives you the best
likelihood. Or you can just use the last iteration.

**Comment by imk1** [comment]
It looks like HDP was not running to completion because of an HDP issue.  I think I fixed that, so hopefully I will get the right output files now.  Thanks for helping me out with this!
